version: '2'
services:
    talarion-app:
        image: talarion
        external_links:
            - talarion-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/talarion
        ports:
            - 8080:8080
    talarion-postgresql:
        extends:
            file: postgresql.yml
            service: talarion-postgresql
